stages:
  - test
  - deploy

# Disable SAST temporarily
variables:
  SAST_DISABLED: "true"

# Test stage
test:
  stage: test
  script:
    - pip install -r requirements.txt
    - python manage.py test

# Deploy stage
deploy:
  stage: deploy
  script:
    - docker-compose down
    - docker-compose up --build -d
  only:
    - master
